# Variables
DATABASE = mariadb
WEBSITE = wordpress
DOCKER_COMPOSE = sudo docker compose
DOCKER_COMPOSE_FOLDER = srcs
FILES_FOLDER = $(HOME)/data
# Couleurs
GREEN=\033[0;32m
YELLOW=\033[1;33m
RED=\033[0;31m
NC=\033[0m
# Commandes

build: 
	@mkdir -p $(FILES_FOLDER)
	@mkdir $(FILES_FOLDER)/$(DATABASE)
	@mkdir $(FILES_FOLDER)/$(WEBSITE)

start:
	@if [ ! -d $(FILES_FOLDER)/$(DATABASE) ]; then \
		printf "$(YELLOW)Construction du projet...$(NC)\n"; \
		make build; \
	fi
	@cd $(DOCKER_COMPOSE_FOLDER) && \
	printf "$(YELLOW)Démarrage du projet...$(NC)\n"; \
	$(DOCKER_COMPOSE) up --build

stop:
	@cd $(DOCKER_COMPOSE_FOLDER) && \
	printf "$(YELLOW)Arrêt du projet...$(NC)\n"; \
	$(DOCKER_COMPOSE) stop && \
	$(DOCKER_COMPOSE) down

clean:  
	@sudo rm -rf $(FILES_FOLDER)/$(DATABASE)/*
	@sudo rm -rf $(FILES_FOLDER)/$(WEBSITE)/*

fclean:  clean
	@sudo rm -rf $(FILES_FOLDER)
	@sudo docker volume rm srcs_mariadb
	@sudo docker volume rm srcs_wordpress

re:
	@make stop && \
	make start

.PHONY: start stop build clean fclean re

.DEFAULT_GOAL :=  start
