CREATE DATABASE IF NOT EXIST 'base'
    DEFAULT CHARACTER SET utf8 COLLATE utf8_bin;
USE base;

CREATE USER 'mysql'@'%' INENTIFIED BY '123456789';
GRANT ALL PRIVILEGES ON *.*D TO 'user42'@'%' WITH GRANT OPTION