CREATE DATABASE IF NOT EXISTS `base`
    DEFAULT CHARACTER SET utf8 COLLATE utf8_bin;
USE base;

CREATE USER 'sajansse'@'%' IDENTIFIED BY '123456789';
CREATE USER 'user42'@'%' IDENTIFIED BY '123456789';
GRANT ALL PRIVILEGES ON *.* TO 'user42'@'%' WITH GRANT OPTION